### ISSUE TITLE
Update Contributing Guidelines

### ISSUE THREAD

**Issue by KaosElegent** [Seneca-Software-Developers-Club/ssdc-website#1]
- Add PR naming convention. (Since that'll be the squashed commit's name). This should be done in `CONTRIBUTING.md`
- Move the `components` folder outside `app` directory. Might need to rework `tsconfig.json`

**Comment by CrisH2307** [comment]
Great, but you can try to run the server and check every routes to make sure it works.

**Comment by KaosElegent** [comment]
The PR for this is #2
