### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by KaosElegent** [Seneca-Software-Developers-Club/ssdc-website#4]
This page's development is quite straightforward. 

- For the images, feel free to use the same images as the dummy website and don't worry too much about both images not being identical in size, etc. as this entire section will be replaced with a carousel in the future before deployment.
- Other than that, feel free also to use all of the existing words and stats.
- If possible, also do the following to the stats:
  - Change `UPCOMING EVENTS` to `PREVIOUS EVENTS`
  - Not sure what the `RESOURCES` should be changed to, but feel free to brainstorm that part. (not necessary though)

![Image](https://github.com/user-attachments/assets/277d63ca-e9bc-4df7-9418-170704dbf662)

**Comment by CrisH2307** [comment]
This issue has been solved in #9
